services:
  ff1_dev_db:
    image: postgres:14.2-alpine3.15
    restart: unless-stopped
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ff1_dev_db
    container_name: ff1_dev_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  ff1_dev_app:
    build: .
    container_name: ff1_dev_app
    restart: unless-stopped
    ports:
      - 4000:4000
    depends_on:
      ff1_dev_db:
        condition: service_healthy
    volumes:
      - .:/usr/src/ff1
